# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    # Check for code to be corrected
    -   id: check-docstring-first
    -   id: check-merge-conflict
    # Check/fix whitespace issues
    -   id: mixed-line-ending
    -   id: name-tests-test
        args: [--django]
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    # Code polish
    -   id: requirements-txt-fixer
    -   id: fix-encoding-pragma
    -   id: check-byte-order-marker
    # Check data files
    -   id: check-xml
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix]
    # Look at file issues
    -   id: check-case-conflict
    -   id: check-added-large-files
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
    -   id: reorder-python-imports
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
    -   id: flake8
        args: [--max-line-length=100]
-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
-   repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1
    hooks:
    -   id: pydocstyle
